export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_FAILURE = "FETCH_FAILURE";
export const FETCH_SUCCESS_USER = "FETCH_SUCCESS_USER";

export const FETCH_SUCCESS_ADS = "FETCH_SUCCESS_ADS";

export const CLEAR_SESSION = "CLEAR_SESSION";
